apiVersion: v1
kind: Service
metadata:
  name: student-crud-service
spec:
  type: NodePort
  selector:
    app: student-crud
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 32000
